// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: marketstore.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	// NOTE: The ordering of this enum must match the File Format order
	//
	// We define our own types here instead of using the (excellent!) built-in Go type system for the primary reason
	// that we are serializing data to files and so need to have a (very!) stable on-disk representation that matches
	// the processing we do internally.
	DataType_UNKNOWN  DataType = 0
	DataType_FLOAT32  DataType = 1
	DataType_INT32    DataType = 2
	DataType_FLOAT64  DataType = 3
	DataType_INT64    DataType = 4
	DataType_EPOCH    DataType = 5
	DataType_BYTE     DataType = 6
	DataType_BOOL     DataType = 7
	DataType_NONE     DataType = 8
	DataType_STRING   DataType = 9
	DataType_INT16    DataType = 10
	DataType_UINT8    DataType = 11
	DataType_UINT16   DataType = 12
	DataType_UINT32   DataType = 13
	DataType_UINT64   DataType = 14
	DataType_STRING16 DataType = 15
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "FLOAT32",
		2:  "INT32",
		3:  "FLOAT64",
		4:  "INT64",
		5:  "EPOCH",
		6:  "BYTE",
		7:  "BOOL",
		8:  "NONE",
		9:  "STRING",
		10: "INT16",
		11: "UINT8",
		12: "UINT16",
		13: "UINT32",
		14: "UINT64",
		15: "STRING16",
	}
	DataType_value = map[string]int32{
		"UNKNOWN":  0,
		"FLOAT32":  1,
		"INT32":    2,
		"FLOAT64":  3,
		"INT64":    4,
		"EPOCH":    5,
		"BYTE":     6,
		"BOOL":     7,
		"NONE":     8,
		"STRING":   9,
		"INT16":    10,
		"UINT8":    11,
		"UINT16":   12,
		"UINT32":   13,
		"UINT64":   14,
		"STRING16": 15,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_marketstore_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_marketstore_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{0}
}

type ListSymbolsRequest_Format int32

const (
	// symbol names (e.g. ["AAPL", "AMZN", ....])
	ListSymbolsRequest_SYMBOL ListSymbolsRequest_Format = 0
	// {symbol/timeframe/attributeGroup} names (e.g. ["AAPL/1Min/TICK", "AAPL/1Sec/OHLCV", "Amazon/1D/Tick",...])
	ListSymbolsRequest_TIME_BUCKET_KEY ListSymbolsRequest_Format = 1
)

// Enum value maps for ListSymbolsRequest_Format.
var (
	ListSymbolsRequest_Format_name = map[int32]string{
		0: "SYMBOL",
		1: "TIME_BUCKET_KEY",
	}
	ListSymbolsRequest_Format_value = map[string]int32{
		"SYMBOL":          0,
		"TIME_BUCKET_KEY": 1,
	}
)

func (x ListSymbolsRequest_Format) Enum() *ListSymbolsRequest_Format {
	p := new(ListSymbolsRequest_Format)
	*p = x
	return p
}

func (x ListSymbolsRequest_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListSymbolsRequest_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_marketstore_proto_enumTypes[1].Descriptor()
}

func (ListSymbolsRequest_Format) Type() protoreflect.EnumType {
	return &file_marketstore_proto_enumTypes[1]
}

func (x ListSymbolsRequest_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListSymbolsRequest_Format.Descriptor instead.
func (ListSymbolsRequest_Format) EnumDescriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{15, 0}
}

type DataShape struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// DataType type = 2;
	// type string such as i4 and f8
	// use string instead of DataType enum in order to align with column_types in NumpyDataset.
	// TODO: use DataType enum at DataShape and NumpyDataset
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataShape) Reset() {
	*x = DataShape{}
	mi := &file_marketstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataShape) ProtoMessage() {}

func (x *DataShape) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataShape.ProtoReflect.Descriptor instead.
func (*DataShape) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{0}
}

func (x *DataShape) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataShape) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type NumpyMultiDataset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *NumpyDataset          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	StartIndex    map[string]int32       `protobuf:"bytes,2,rep,name=start_index,json=startIndex,proto3" json:"start_index,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Lengths       map[string]int32       `protobuf:"bytes,3,rep,name=lengths,proto3" json:"lengths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumpyMultiDataset) Reset() {
	*x = NumpyMultiDataset{}
	mi := &file_marketstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumpyMultiDataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumpyMultiDataset) ProtoMessage() {}

func (x *NumpyMultiDataset) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumpyMultiDataset.ProtoReflect.Descriptor instead.
func (*NumpyMultiDataset) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{1}
}

func (x *NumpyMultiDataset) GetData() *NumpyDataset {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *NumpyMultiDataset) GetStartIndex() map[string]int32 {
	if x != nil {
		return x.StartIndex
	}
	return nil
}

func (x *NumpyMultiDataset) GetLengths() map[string]int32 {
	if x != nil {
		return x.Lengths
	}
	return nil
}

type NumpyDataset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// a list of type strings such as i4 and f8
	ColumnTypes []string `protobuf:"bytes,1,rep,name=column_types,json=columnTypes,proto3" json:"column_types,omitempty"`
	// a list of column names
	ColumnNames []string `protobuf:"bytes,2,rep,name=column_names,json=columnNames,proto3" json:"column_names,omitempty"`
	// two dimentional byte arrays holding the column data
	ColumnData [][]byte `protobuf:"bytes,3,rep,name=column_data,json=columnData,proto3" json:"column_data,omitempty"`
	Length     int32    `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	// hidden
	DataShapes    []*DataShape `protobuf:"bytes,5,rep,name=data_shapes,json=dataShapes,proto3" json:"data_shapes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumpyDataset) Reset() {
	*x = NumpyDataset{}
	mi := &file_marketstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumpyDataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumpyDataset) ProtoMessage() {}

func (x *NumpyDataset) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumpyDataset.ProtoReflect.Descriptor instead.
func (*NumpyDataset) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{2}
}

func (x *NumpyDataset) GetColumnTypes() []string {
	if x != nil {
		return x.ColumnTypes
	}
	return nil
}

func (x *NumpyDataset) GetColumnNames() []string {
	if x != nil {
		return x.ColumnNames
	}
	return nil
}

func (x *NumpyDataset) GetColumnData() [][]byte {
	if x != nil {
		return x.ColumnData
	}
	return nil
}

func (x *NumpyDataset) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *NumpyDataset) GetDataShapes() []*DataShape {
	if x != nil {
		return x.DataShapes
	}
	return nil
}

type CreateRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Key        string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // a time bucket key
	DataShapes []*DataShape           `protobuf:"bytes,2,rep,name=data_shapes,json=dataShapes,proto3" json:"data_shapes,omitempty"`
	RowType    string                 `protobuf:"bytes,3,opt,name=row_type,json=rowType,proto3" json:"row_type,omitempty"` // fixed or variable
	// If true, the request schema overrides any configured attrgroup_types schema.
	// If false (default), the config schema takes precedence when defined.
	OverrideSchema bool `protobuf:"varint,4,opt,name=override_schema,json=overrideSchema,proto3" json:"override_schema,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_marketstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateRequest) GetDataShapes() []*DataShape {
	if x != nil {
		return x.DataShapes
	}
	return nil
}

func (x *CreateRequest) GetRowType() string {
	if x != nil {
		return x.RowType
	}
	return ""
}

func (x *CreateRequest) GetOverrideSchema() bool {
	if x != nil {
		return x.OverrideSchema
	}
	return false
}

type MultiCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*CreateRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiCreateRequest) Reset() {
	*x = MultiCreateRequest{}
	mi := &file_marketstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiCreateRequest) ProtoMessage() {}

func (x *MultiCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiCreateRequest.ProtoReflect.Descriptor instead.
func (*MultiCreateRequest) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{4}
}

func (x *MultiCreateRequest) GetRequests() []*CreateRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type MultiQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A multi-request allows for different Timeframes and record formats for each request
	Requests      []*QueryRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiQueryRequest) Reset() {
	*x = MultiQueryRequest{}
	mi := &file_marketstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiQueryRequest) ProtoMessage() {}

func (x *MultiQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiQueryRequest.ProtoReflect.Descriptor instead.
func (*MultiQueryRequest) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{5}
}

func (x *MultiQueryRequest) GetRequests() []*QueryRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Note: SQL is not fully supported
	IsSqlStatement bool   `protobuf:"varint,1,opt,name=is_sql_statement,json=isSqlStatement,proto3" json:"is_sql_statement,omitempty"` // If this is a SQL request, Only SQLStatement is relevant
	SqlStatement   string `protobuf:"bytes,2,opt,name=sql_statement,json=sqlStatement,proto3" json:"sql_statement,omitempty"`
	// Destination is <symbol>/<timeframe>/<attributegroup>
	Destination string `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	// This is not usually set, defaults to Symbol/Timeframe/AttributeGroup
	KeyCategory string `protobuf:"bytes,4,opt,name=key_category,json=keyCategory,proto3" json:"key_category,omitempty"`
	// Lower time predicate (i.e. index >= start) in unix epoch second
	EpochStart int64 `protobuf:"varint,5,opt,name=epoch_start,json=epochStart,proto3" json:"epoch_start,omitempty"`
	// fractional part (nano second) of epoch_start
	EpochStartNanos int64 `protobuf:"varint,6,opt,name=epoch_start_nanos,json=epochStartNanos,proto3" json:"epoch_start_nanos,omitempty"`
	// Upper time predicate (i.e. index <= end) in unix epoch second
	EpochEnd int64 `protobuf:"varint,7,opt,name=epoch_end,json=epochEnd,proto3" json:"epoch_end,omitempty"`
	// fractional part (nano second) of epoch_end
	EpochEndNanos int64 `protobuf:"varint,8,opt,name=epoch_end_nanos,json=epochEndNanos,proto3" json:"epoch_end_nanos,omitempty"`
	// Number of max returned rows from lower/upper bound
	LimitRecordCount int32 `protobuf:"varint,9,opt,name=limit_record_count,json=limitRecordCount,proto3" json:"limit_record_count,omitempty"`
	// Set to true if LimitRecordCount should be from the lower
	LimitFromStart bool `protobuf:"varint,10,opt,name=limit_from_start,json=limitFromStart,proto3" json:"limit_from_start,omitempty"`
	// Array of column names to be returned
	Columns []string `protobuf:"bytes,11,rep,name=columns,proto3" json:"columns,omitempty"`
	// Support for functions is experimental and subject to change
	Functions     []string `protobuf:"bytes,12,rep,name=functions,proto3" json:"functions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_marketstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{6}
}

func (x *QueryRequest) GetIsSqlStatement() bool {
	if x != nil {
		return x.IsSqlStatement
	}
	return false
}

func (x *QueryRequest) GetSqlStatement() string {
	if x != nil {
		return x.SqlStatement
	}
	return ""
}

func (x *QueryRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *QueryRequest) GetKeyCategory() string {
	if x != nil {
		return x.KeyCategory
	}
	return ""
}

func (x *QueryRequest) GetEpochStart() int64 {
	if x != nil {
		return x.EpochStart
	}
	return 0
}

func (x *QueryRequest) GetEpochStartNanos() int64 {
	if x != nil {
		return x.EpochStartNanos
	}
	return 0
}

func (x *QueryRequest) GetEpochEnd() int64 {
	if x != nil {
		return x.EpochEnd
	}
	return 0
}

func (x *QueryRequest) GetEpochEndNanos() int64 {
	if x != nil {
		return x.EpochEndNanos
	}
	return 0
}

func (x *QueryRequest) GetLimitRecordCount() int32 {
	if x != nil {
		return x.LimitRecordCount
	}
	return 0
}

func (x *QueryRequest) GetLimitFromStart() bool {
	if x != nil {
		return x.LimitFromStart
	}
	return false
}

func (x *QueryRequest) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryRequest) GetFunctions() []string {
	if x != nil {
		return x.Functions
	}
	return nil
}

type MultiQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*QueryResponse       `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // Server Version
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiQueryResponse) Reset() {
	*x = MultiQueryResponse{}
	mi := &file_marketstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiQueryResponse) ProtoMessage() {}

func (x *MultiQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiQueryResponse.ProtoReflect.Descriptor instead.
func (*MultiQueryResponse) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{7}
}

func (x *MultiQueryResponse) GetResponses() []*QueryResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *MultiQueryResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MultiQueryResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *NumpyMultiDataset     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_marketstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{8}
}

func (x *QueryResponse) GetResult() *NumpyMultiDataset {
	if x != nil {
		return x.Result
	}
	return nil
}

type MultiWriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A multi-request allows for different Timeframes and record formats for each request
	Requests      []*WriteRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiWriteRequest) Reset() {
	*x = MultiWriteRequest{}
	mi := &file_marketstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiWriteRequest) ProtoMessage() {}

func (x *MultiWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiWriteRequest.ProtoReflect.Descriptor instead.
func (*MultiWriteRequest) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{9}
}

func (x *MultiWriteRequest) GetRequests() []*WriteRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type WriteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Data             *NumpyMultiDataset     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	IsVariableLength bool                   `protobuf:"varint,2,opt,name=is_variable_length,json=isVariableLength,proto3" json:"is_variable_length,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_marketstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{10}
}

func (x *WriteRequest) GetData() *NumpyMultiDataset {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteRequest) GetIsVariableLength() bool {
	if x != nil {
		return x.IsVariableLength
	}
	return false
}

type MultiServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*ServerResponse      `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiServerResponse) Reset() {
	*x = MultiServerResponse{}
	mi := &file_marketstore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiServerResponse) ProtoMessage() {}

func (x *MultiServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiServerResponse.ProtoReflect.Descriptor instead.
func (*MultiServerResponse) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{11}
}

func (x *MultiServerResponse) GetResponses() []*ServerResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // Server Version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_marketstore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{12}
}

func (x *ServerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ServerResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type MultiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*KeyRequest          `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiKeyRequest) Reset() {
	*x = MultiKeyRequest{}
	mi := &file_marketstore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiKeyRequest) ProtoMessage() {}

func (x *MultiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiKeyRequest.ProtoReflect.Descriptor instead.
func (*MultiKeyRequest) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{13}
}

func (x *MultiKeyRequest) GetRequests() []*KeyRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type KeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRequest) Reset() {
	*x = KeyRequest{}
	mi := &file_marketstore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRequest) ProtoMessage() {}

func (x *KeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRequest.ProtoReflect.Descriptor instead.
func (*KeyRequest) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{14}
}

func (x *KeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ListSymbolsRequest struct {
	state  protoimpl.MessageState    `protogen:"open.v1"`
	Format ListSymbolsRequest_Format `protobuf:"varint,1,opt,name=format,proto3,enum=proto.ListSymbolsRequest_Format" json:"format,omitempty"`
	// Optional: filter to symbols that have data for this timeframe (e.g. "1Min", "1D")
	Timeframe string `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	// Optional: filter to symbols that have data on this specific date.
	// Accepts either "YYYY-MM-DD" format or unix epoch seconds as a string (e.g. "2024-01-15" or "1705276800")
	Date          string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSymbolsRequest) Reset() {
	*x = ListSymbolsRequest{}
	mi := &file_marketstore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSymbolsRequest) ProtoMessage() {}

func (x *ListSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSymbolsRequest.ProtoReflect.Descriptor instead.
func (*ListSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{15}
}

func (x *ListSymbolsRequest) GetFormat() ListSymbolsRequest_Format {
	if x != nil {
		return x.Format
	}
	return ListSymbolsRequest_SYMBOL
}

func (x *ListSymbolsRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *ListSymbolsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ListSymbolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []string               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSymbolsResponse) Reset() {
	*x = ListSymbolsResponse{}
	mi := &file_marketstore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSymbolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSymbolsResponse) ProtoMessage() {}

func (x *ListSymbolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSymbolsResponse.ProtoReflect.Descriptor instead.
func (*ListSymbolsResponse) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{16}
}

func (x *ListSymbolsResponse) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

type ServerVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerVersionRequest) Reset() {
	*x = ServerVersionRequest{}
	mi := &file_marketstore_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerVersionRequest) ProtoMessage() {}

func (x *ServerVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerVersionRequest.ProtoReflect.Descriptor instead.
func (*ServerVersionRequest) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{17}
}

type ServerVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerVersionResponse) Reset() {
	*x = ServerVersionResponse{}
	mi := &file_marketstore_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerVersionResponse) ProtoMessage() {}

func (x *ServerVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerVersionResponse.ProtoReflect.Descriptor instead.
func (*ServerVersionResponse) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{18}
}

func (x *ServerVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ListWatchlistsRequest optionally filters to a specific watchlist by name.
// If name is empty, all watchlists are returned.
type ListWatchlistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWatchlistsRequest) Reset() {
	*x = ListWatchlistsRequest{}
	mi := &file_marketstore_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWatchlistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchlistsRequest) ProtoMessage() {}

func (x *ListWatchlistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchlistsRequest.ProtoReflect.Descriptor instead.
func (*ListWatchlistsRequest) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{19}
}

func (x *ListWatchlistsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// WatchlistEntry is a single ranked symbol in a watchlist.
type WatchlistEntry struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Symbol string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Rank   int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	// Strategy-specific fields (e.g. "pct_change", "volume").
	Fields        map[string]float64 `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchlistEntry) Reset() {
	*x = WatchlistEntry{}
	mi := &file_marketstore_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchlistEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchlistEntry) ProtoMessage() {}

func (x *WatchlistEntry) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchlistEntry.ProtoReflect.Descriptor instead.
func (*WatchlistEntry) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{20}
}

func (x *WatchlistEntry) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *WatchlistEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *WatchlistEntry) GetFields() map[string]float64 {
	if x != nil {
		return x.Fields
	}
	return nil
}

// WatchlistRanking is a named watchlist with its current ranked entries.
type WatchlistRanking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Entries       []*WatchlistEntry      `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchlistRanking) Reset() {
	*x = WatchlistRanking{}
	mi := &file_marketstore_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchlistRanking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchlistRanking) ProtoMessage() {}

func (x *WatchlistRanking) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchlistRanking.ProtoReflect.Descriptor instead.
func (*WatchlistRanking) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{21}
}

func (x *WatchlistRanking) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WatchlistRanking) GetEntries() []*WatchlistEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ListWatchlistsResponse contains the current rankings for one or more watchlists.
type ListWatchlistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Watchlists    []*WatchlistRanking    `protobuf:"bytes,1,rep,name=watchlists,proto3" json:"watchlists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWatchlistsResponse) Reset() {
	*x = ListWatchlistsResponse{}
	mi := &file_marketstore_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWatchlistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchlistsResponse) ProtoMessage() {}

func (x *ListWatchlistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketstore_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchlistsResponse.ProtoReflect.Descriptor instead.
func (*ListWatchlistsResponse) Descriptor() ([]byte, []int) {
	return file_marketstore_proto_rawDescGZIP(), []int{22}
}

func (x *ListWatchlistsResponse) GetWatchlists() []*WatchlistRanking {
	if x != nil {
		return x.Watchlists
	}
	return nil
}

var File_marketstore_proto protoreflect.FileDescriptor

const file_marketstore_proto_rawDesc = "" +
	"\n" +
	"\x11marketstore.proto\x12\x05proto\"3\n" +
	"\tDataShape\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xc3\x02\n" +
	"\x11NumpyMultiDataset\x12'\n" +
	"\x04data\x18\x01 \x01(\v2\x13.proto.NumpyDatasetR\x04data\x12I\n" +
	"\vstart_index\x18\x02 \x03(\v2(.proto.NumpyMultiDataset.StartIndexEntryR\n" +
	"startIndex\x12?\n" +
	"\alengths\x18\x03 \x03(\v2%.proto.NumpyMultiDataset.LengthsEntryR\alengths\x1a=\n" +
	"\x0fStartIndexEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a:\n" +
	"\fLengthsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xc0\x01\n" +
	"\fNumpyDataset\x12!\n" +
	"\fcolumn_types\x18\x01 \x03(\tR\vcolumnTypes\x12!\n" +
	"\fcolumn_names\x18\x02 \x03(\tR\vcolumnNames\x12\x1f\n" +
	"\vcolumn_data\x18\x03 \x03(\fR\n" +
	"columnData\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x05R\x06length\x121\n" +
	"\vdata_shapes\x18\x05 \x03(\v2\x10.proto.DataShapeR\n" +
	"dataShapes\"\x98\x01\n" +
	"\rCreateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\vdata_shapes\x18\x02 \x03(\v2\x10.proto.DataShapeR\n" +
	"dataShapes\x12\x19\n" +
	"\brow_type\x18\x03 \x01(\tR\arowType\x12'\n" +
	"\x0foverride_schema\x18\x04 \x01(\bR\x0eoverrideSchema\"F\n" +
	"\x12MultiCreateRequest\x120\n" +
	"\brequests\x18\x01 \x03(\v2\x14.proto.CreateRequestR\brequests\"D\n" +
	"\x11MultiQueryRequest\x12/\n" +
	"\brequests\x18\x01 \x03(\v2\x13.proto.QueryRequestR\brequests\"\xc4\x03\n" +
	"\fQueryRequest\x12(\n" +
	"\x10is_sql_statement\x18\x01 \x01(\bR\x0eisSqlStatement\x12#\n" +
	"\rsql_statement\x18\x02 \x01(\tR\fsqlStatement\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12!\n" +
	"\fkey_category\x18\x04 \x01(\tR\vkeyCategory\x12\x1f\n" +
	"\vepoch_start\x18\x05 \x01(\x03R\n" +
	"epochStart\x12*\n" +
	"\x11epoch_start_nanos\x18\x06 \x01(\x03R\x0fepochStartNanos\x12\x1b\n" +
	"\tepoch_end\x18\a \x01(\x03R\bepochEnd\x12&\n" +
	"\x0fepoch_end_nanos\x18\b \x01(\x03R\repochEndNanos\x12,\n" +
	"\x12limit_record_count\x18\t \x01(\x05R\x10limitRecordCount\x12(\n" +
	"\x10limit_from_start\x18\n" +
	" \x01(\bR\x0elimitFromStart\x12\x18\n" +
	"\acolumns\x18\v \x03(\tR\acolumns\x12\x1c\n" +
	"\tfunctions\x18\f \x03(\tR\tfunctions\"~\n" +
	"\x12MultiQueryResponse\x122\n" +
	"\tresponses\x18\x01 \x03(\v2\x14.proto.QueryResponseR\tresponses\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\"A\n" +
	"\rQueryResponse\x120\n" +
	"\x06result\x18\x01 \x01(\v2\x18.proto.NumpyMultiDatasetR\x06result\"D\n" +
	"\x11MultiWriteRequest\x12/\n" +
	"\brequests\x18\x01 \x03(\v2\x13.proto.WriteRequestR\brequests\"j\n" +
	"\fWriteRequest\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.proto.NumpyMultiDatasetR\x04data\x12,\n" +
	"\x12is_variable_length\x18\x02 \x01(\bR\x10isVariableLength\"J\n" +
	"\x13MultiServerResponse\x123\n" +
	"\tresponses\x18\x01 \x03(\v2\x15.proto.ServerResponseR\tresponses\"@\n" +
	"\x0eServerResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"@\n" +
	"\x0fMultiKeyRequest\x12-\n" +
	"\brequests\x18\x01 \x03(\v2\x11.proto.KeyRequestR\brequests\"\x1e\n" +
	"\n" +
	"KeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xab\x01\n" +
	"\x12ListSymbolsRequest\x128\n" +
	"\x06format\x18\x01 \x01(\x0e2 .proto.ListSymbolsRequest.FormatR\x06format\x12\x1c\n" +
	"\ttimeframe\x18\x02 \x01(\tR\ttimeframe\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\")\n" +
	"\x06Format\x12\n" +
	"\n" +
	"\x06SYMBOL\x10\x00\x12\x13\n" +
	"\x0fTIME_BUCKET_KEY\x10\x01\"/\n" +
	"\x13ListSymbolsResponse\x12\x18\n" +
	"\aresults\x18\x01 \x03(\tR\aresults\"\x16\n" +
	"\x14ServerVersionRequest\"1\n" +
	"\x15ServerVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"+\n" +
	"\x15ListWatchlistsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xb2\x01\n" +
	"\x0eWatchlistEntry\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\x129\n" +
	"\x06fields\x18\x03 \x03(\v2!.proto.WatchlistEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"W\n" +
	"\x10WatchlistRanking\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\aentries\x18\x02 \x03(\v2\x15.proto.WatchlistEntryR\aentries\"Q\n" +
	"\x16ListWatchlistsResponse\x127\n" +
	"\n" +
	"watchlists\x18\x01 \x03(\v2\x17.proto.WatchlistRankingR\n" +
	"watchlists*\xc4\x01\n" +
	"\bDataType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aFLOAT32\x10\x01\x12\t\n" +
	"\x05INT32\x10\x02\x12\v\n" +
	"\aFLOAT64\x10\x03\x12\t\n" +
	"\x05INT64\x10\x04\x12\t\n" +
	"\x05EPOCH\x10\x05\x12\b\n" +
	"\x04BYTE\x10\x06\x12\b\n" +
	"\x04BOOL\x10\a\x12\b\n" +
	"\x04NONE\x10\b\x12\n" +
	"\n" +
	"\x06STRING\x10\t\x12\t\n" +
	"\x05INT16\x10\n" +
	"\x12\t\n" +
	"\x05UINT8\x10\v\x12\n" +
	"\n" +
	"\x06UINT16\x10\f\x12\n" +
	"\n" +
	"\x06UINT32\x10\r\x12\n" +
	"\n" +
	"\x06UINT64\x10\x0e\x12\f\n" +
	"\bSTRING16\x10\x0f2\xeb\x03\n" +
	"\vMarketstore\x12<\n" +
	"\x05Query\x12\x18.proto.MultiQueryRequest\x1a\x19.proto.MultiQueryResponse\x12?\n" +
	"\x06Create\x12\x19.proto.MultiCreateRequest\x1a\x1a.proto.MultiServerResponse\x12=\n" +
	"\x05Write\x12\x18.proto.MultiWriteRequest\x1a\x1a.proto.MultiServerResponse\x12=\n" +
	"\aDestroy\x12\x16.proto.MultiKeyRequest\x1a\x1a.proto.MultiServerResponse\x12D\n" +
	"\vListSymbols\x12\x19.proto.ListSymbolsRequest\x1a\x1a.proto.ListSymbolsResponse\x12J\n" +
	"\rServerVersion\x12\x1b.proto.ServerVersionRequest\x1a\x1c.proto.ServerVersionResponse\x12M\n" +
	"\x0eListWatchlists\x12\x1c.proto.ListWatchlistsRequest\x1a\x1d.proto.ListWatchlistsResponseB'Z%github.com/alpacahq/marketstore/protob\x06proto3"

var (
	file_marketstore_proto_rawDescOnce sync.Once
	file_marketstore_proto_rawDescData []byte
)

func file_marketstore_proto_rawDescGZIP() []byte {
	file_marketstore_proto_rawDescOnce.Do(func() {
		file_marketstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketstore_proto_rawDesc), len(file_marketstore_proto_rawDesc)))
	})
	return file_marketstore_proto_rawDescData
}

var file_marketstore_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_marketstore_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_marketstore_proto_goTypes = []any{
	(DataType)(0),                  // 0: proto.DataType
	(ListSymbolsRequest_Format)(0), // 1: proto.ListSymbolsRequest.Format
	(*DataShape)(nil),              // 2: proto.DataShape
	(*NumpyMultiDataset)(nil),      // 3: proto.NumpyMultiDataset
	(*NumpyDataset)(nil),           // 4: proto.NumpyDataset
	(*CreateRequest)(nil),          // 5: proto.CreateRequest
	(*MultiCreateRequest)(nil),     // 6: proto.MultiCreateRequest
	(*MultiQueryRequest)(nil),      // 7: proto.MultiQueryRequest
	(*QueryRequest)(nil),           // 8: proto.QueryRequest
	(*MultiQueryResponse)(nil),     // 9: proto.MultiQueryResponse
	(*QueryResponse)(nil),          // 10: proto.QueryResponse
	(*MultiWriteRequest)(nil),      // 11: proto.MultiWriteRequest
	(*WriteRequest)(nil),           // 12: proto.WriteRequest
	(*MultiServerResponse)(nil),    // 13: proto.MultiServerResponse
	(*ServerResponse)(nil),         // 14: proto.ServerResponse
	(*MultiKeyRequest)(nil),        // 15: proto.MultiKeyRequest
	(*KeyRequest)(nil),             // 16: proto.KeyRequest
	(*ListSymbolsRequest)(nil),     // 17: proto.ListSymbolsRequest
	(*ListSymbolsResponse)(nil),    // 18: proto.ListSymbolsResponse
	(*ServerVersionRequest)(nil),   // 19: proto.ServerVersionRequest
	(*ServerVersionResponse)(nil),  // 20: proto.ServerVersionResponse
	(*ListWatchlistsRequest)(nil),  // 21: proto.ListWatchlistsRequest
	(*WatchlistEntry)(nil),         // 22: proto.WatchlistEntry
	(*WatchlistRanking)(nil),       // 23: proto.WatchlistRanking
	(*ListWatchlistsResponse)(nil), // 24: proto.ListWatchlistsResponse
	nil,                            // 25: proto.NumpyMultiDataset.StartIndexEntry
	nil,                            // 26: proto.NumpyMultiDataset.LengthsEntry
	nil,                            // 27: proto.WatchlistEntry.FieldsEntry
}
var file_marketstore_proto_depIdxs = []int32{
	4,  // 0: proto.NumpyMultiDataset.data:type_name -> proto.NumpyDataset
	25, // 1: proto.NumpyMultiDataset.start_index:type_name -> proto.NumpyMultiDataset.StartIndexEntry
	26, // 2: proto.NumpyMultiDataset.lengths:type_name -> proto.NumpyMultiDataset.LengthsEntry
	2,  // 3: proto.NumpyDataset.data_shapes:type_name -> proto.DataShape
	2,  // 4: proto.CreateRequest.data_shapes:type_name -> proto.DataShape
	5,  // 5: proto.MultiCreateRequest.requests:type_name -> proto.CreateRequest
	8,  // 6: proto.MultiQueryRequest.requests:type_name -> proto.QueryRequest
	10, // 7: proto.MultiQueryResponse.responses:type_name -> proto.QueryResponse
	3,  // 8: proto.QueryResponse.result:type_name -> proto.NumpyMultiDataset
	12, // 9: proto.MultiWriteRequest.requests:type_name -> proto.WriteRequest
	3,  // 10: proto.WriteRequest.data:type_name -> proto.NumpyMultiDataset
	14, // 11: proto.MultiServerResponse.responses:type_name -> proto.ServerResponse
	16, // 12: proto.MultiKeyRequest.requests:type_name -> proto.KeyRequest
	1,  // 13: proto.ListSymbolsRequest.format:type_name -> proto.ListSymbolsRequest.Format
	27, // 14: proto.WatchlistEntry.fields:type_name -> proto.WatchlistEntry.FieldsEntry
	22, // 15: proto.WatchlistRanking.entries:type_name -> proto.WatchlistEntry
	23, // 16: proto.ListWatchlistsResponse.watchlists:type_name -> proto.WatchlistRanking
	7,  // 17: proto.Marketstore.Query:input_type -> proto.MultiQueryRequest
	6,  // 18: proto.Marketstore.Create:input_type -> proto.MultiCreateRequest
	11, // 19: proto.Marketstore.Write:input_type -> proto.MultiWriteRequest
	15, // 20: proto.Marketstore.Destroy:input_type -> proto.MultiKeyRequest
	17, // 21: proto.Marketstore.ListSymbols:input_type -> proto.ListSymbolsRequest
	19, // 22: proto.Marketstore.ServerVersion:input_type -> proto.ServerVersionRequest
	21, // 23: proto.Marketstore.ListWatchlists:input_type -> proto.ListWatchlistsRequest
	9,  // 24: proto.Marketstore.Query:output_type -> proto.MultiQueryResponse
	13, // 25: proto.Marketstore.Create:output_type -> proto.MultiServerResponse
	13, // 26: proto.Marketstore.Write:output_type -> proto.MultiServerResponse
	13, // 27: proto.Marketstore.Destroy:output_type -> proto.MultiServerResponse
	18, // 28: proto.Marketstore.ListSymbols:output_type -> proto.ListSymbolsResponse
	20, // 29: proto.Marketstore.ServerVersion:output_type -> proto.ServerVersionResponse
	24, // 30: proto.Marketstore.ListWatchlists:output_type -> proto.ListWatchlistsResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_marketstore_proto_init() }
func file_marketstore_proto_init() {
	if File_marketstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketstore_proto_rawDesc), len(file_marketstore_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketstore_proto_goTypes,
		DependencyIndexes: file_marketstore_proto_depIdxs,
		EnumInfos:         file_marketstore_proto_enumTypes,
		MessageInfos:      file_marketstore_proto_msgTypes,
	}.Build()
	File_marketstore_proto = out.File
	file_marketstore_proto_goTypes = nil
	file_marketstore_proto_depIdxs = nil
}
