// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: replication.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteAheadLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteAheadLog) Reset() {
	*x = WriteAheadLog{}
	mi := &file_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAheadLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAheadLog) ProtoMessage() {}

func (x *WriteAheadLog) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAheadLog.ProtoReflect.Descriptor instead.
func (*WriteAheadLog) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{0}
}

type GetWALStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWALStreamRequest) Reset() {
	*x = GetWALStreamRequest{}
	mi := &file_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWALStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWALStreamRequest) ProtoMessage() {}

func (x *GetWALStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWALStreamRequest.ProtoReflect.Descriptor instead.
func (*GetWALStreamRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{1}
}

type GetWALStreamResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransactionGroup []byte                 `protobuf:"bytes,1,opt,name=transaction_group,json=transactionGroup,proto3" json:"transaction_group,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetWALStreamResponse) Reset() {
	*x = GetWALStreamResponse{}
	mi := &file_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWALStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWALStreamResponse) ProtoMessage() {}

func (x *GetWALStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWALStreamResponse.ProtoReflect.Descriptor instead.
func (*GetWALStreamResponse) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{2}
}

func (x *GetWALStreamResponse) GetTransactionGroup() []byte {
	if x != nil {
		return x.TransactionGroup
	}
	return nil
}

var File_replication_proto protoreflect.FileDescriptor

const file_replication_proto_rawDesc = "" +
	"\n" +
	"\x11replication.proto\x12\x05proto\"\x0f\n" +
	"\rWriteAheadLog\"\x15\n" +
	"\x13GetWALStreamRequest\"C\n" +
	"\x14GetWALStreamResponse\x12+\n" +
	"\x11transaction_group\x18\x01 \x01(\fR\x10transactionGroup2X\n" +
	"\vReplication\x12I\n" +
	"\fGetWALStream\x12\x1a.proto.GetWALStreamRequest\x1a\x1b.proto.GetWALStreamResponse0\x01B'Z%github.com/alpacahq/marketstore/protob\x06proto3"

var (
	file_replication_proto_rawDescOnce sync.Once
	file_replication_proto_rawDescData []byte
)

func file_replication_proto_rawDescGZIP() []byte {
	file_replication_proto_rawDescOnce.Do(func() {
		file_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replication_proto_rawDesc), len(file_replication_proto_rawDesc)))
	})
	return file_replication_proto_rawDescData
}

var file_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_replication_proto_goTypes = []any{
	(*WriteAheadLog)(nil),        // 0: proto.WriteAheadLog
	(*GetWALStreamRequest)(nil),  // 1: proto.GetWALStreamRequest
	(*GetWALStreamResponse)(nil), // 2: proto.GetWALStreamResponse
}
var file_replication_proto_depIdxs = []int32{
	1, // 0: proto.Replication.GetWALStream:input_type -> proto.GetWALStreamRequest
	2, // 1: proto.Replication.GetWALStream:output_type -> proto.GetWALStreamResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_replication_proto_init() }
func file_replication_proto_init() {
	if File_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replication_proto_rawDesc), len(file_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replication_proto_goTypes,
		DependencyIndexes: file_replication_proto_depIdxs,
		MessageInfos:      file_replication_proto_msgTypes,
	}.Build()
	File_replication_proto = out.File
	file_replication_proto_goTypes = nil
	file_replication_proto_depIdxs = nil
}
